version: "3.8"

services:
  client:
    build:
      context: ./client
    volumes:
      - ./client:/app

  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - "8055:8055"
    depends_on:
      - client
