services:
  client:
    build:
      context: ./client
    volumes:
      - shared-data:/app/dist

  api:
    build:
      context: ./api
    volumes:
      - shared-data:/app/views
      - ./api/uploads:/app/uploads

    ports:
      - "8055:8055"

volumes:
  shared-data:
