services:
  dev:
    build:
      context: .
      target: development
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev
    restart: unless-stopped

  build:
    build:
      context: .
      target: builder
    env_file:
      - .env
    command: npm run build
    volumes:
      - .:/app
    restart: "no"

  prod:
    build:
      context: .
      target: production
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
